### ISSUE TITLE
Sample project

### ISSUE THREAD

**Issue by ygdrasil-io** [vova7878/PanamaPort#1]
Hello, great initiative! 

Are there any sample projects or demos available to assess the library's current capabilities?

**Comment by vova7878** [comment]
Hello!
Unfortunately I only have an ugly test app locally, I need help writing tests, the project is too big

**Comment by vova7878** [comment]
>  demos available to assess the library's current capabilities?

In theory, the API is just ctrl-c ctrl-v from the hotspot implementation of panama, if you are familiar with it, then you only need to change the package name in your code. 

The only problem might be with adding the library to the project, but it simply includes via jitpack.io and an example of this is in my next library - AndroidVMTools

**Comment by vova7878** [comment]
I've created a repository where I'll add tests and examples as they're created.

https://github.com/vova7878/PanamaExamples

**Comment by ygdrasil-io** [comment]
Thanks for the reactivity.

I try the test project and I get the error :

```
PanamaExamples/HelloFromPanama/src/main/java/com/v7878/hellopanama/MainActivity.java:3: error: cannot access ValueLayout
import static com.v7878.foreign.ValueLayout.ADDRESS;
                               ^
  bad class file: /Users/chaos/.gradle/caches/transforms-4/3a4d102a5727096668aff7e0e478f69b/transformed/AndroidPanama-v0.0.4-preview-api.jar(/com/v7878/foreign/ValueLayout.class)
    class file has wrong version 65.0, should be 61.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Library has been compiled to target Java 21 but as far as I know, only Java 17- is supported according to the documentation, 
https://developer.android.com/build/jdks

I'm missing something ?

**Comment by vova7878** [comment]
>Java 17- is supported according to the documentation

Standard library support is indeed at jdk17 level, but the maximum version for compilation is much higher.

I was forced to use jdk21 because it is required for the hotspot part of the code (and documentation) that I used in the implementation

**Comment by ygdrasil-io** [comment]
Indeed, that working well after switching to JDK 21. 

I'm currently working on a large codebase library https://github.com/wgpu4k/wgpu4k and the JNI part will be hard to maintain, while this is more easier with Panama on JVM side. I need to finish the JNI part to get a stable first release but after I will definitly try wih this project. I guess we will get in touch on the incoming months.

**Comment by vova7878** [comment]
Have already seen your project, if my library is useful to you, I will be glad. 

I'm confused that because the package name is different, you will have to make a separate branch for android, although this could be avoided (probably)

P.S. If you need to contact me, there is a link to my telegram account in my profile

**Comment by vova7878** [comment]
I have completed porting the tests from the OpenJ9 implementation and have started porting the Hotspot tests

https://github.com/vova7878/PanamaExamples/tree/main/OpenJ9AndHotspotTests
